### ISSUE TITLE
upnp无效

### ISSUE THREAD

**Issue by woweek** [ioiotor/mir4-ss#2]
一直在用大佬的固件，最近升了新版，因为迅雷下载的慢，所以”下载诊断“了下才发现，迅雷里的”Upnp状态查询“失败，按照官方盒lean issue都查了也没能解决，另外您的两个版本都试过了也无法生效。

我这是光猫桥接给路由器拨号，路由里是openwrt的方案。

想请问，您自己那upnp有效不？

**Comment by ioiotor** [comment]
@woweek  手动安装一下 upnp就好了 比如带中文界面的  luci-i18n-upnp-zh-cn 会自动安装 miniupnpd包
opkg install luci-i18n-upnp-zh-cn
