### ISSUE TITLE
Merge Xiaomi Mi Router 4 support into main project

### ISSUE THREAD

**Issue by sequentiality** [ioiotor/mir4-ss#3]
Many thanks for v19.07.4 for mir4!

@ioiotor @soikjk I was wondering if you have plans to merge your work into the main project?

@inflabz created PR for adding support for mi4: https://github.com/openwrt/openwrt/pull/3330
@adschm added it to his staging: https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/mir4

Thanks for your work and hope you'll collaborate to merge it.

**Comment by adschm** [comment]
> @adschm added it to his staging: https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/mir4

Yes, in October, for further discussion, but nobody discussed it since then.

**Comment by ioiotor** [comment]
@adschm  @sequentiality https://github.com/ioiotor/openwrt/commit/d02f1beb7750fd707eccf227a5ece325f9f5e653

**Comment by ioiotor** [comment]
Sorry My English is not good. You can make a patch if you want. 

according to
https://github.com/ioiotor/openwrt/commit/d02f1beb7750fd707eccf227a5ece325f9f5e653

@inflabz created PR for adding support for mi4: openwrt/openwrt#3330

**Comment by adschm** [comment]
The PR from inflabz has stalled, since he does not own the device anymore. Somebody will have to take up the work and finalize device support.

**Comment by ioiotor** [comment]
@adschm 
It works fine in my xiaomi router 4  What can I do if you need to

**Comment by sequentiality** [comment]
@adschm is something additional required to merge ioiotor/openwrt@d02f1be ?

**Comment by adschm** [comment]
I'm OpenWrt maintainer, so be aware that I only refer to the pull request against the official repo. That one was closed due to inactivity by the original author. It's just not finished and nobody wanted to continue. If you want to comment with respect to that "official" PR, please do it there:

https://github.com/openwrt/openwrt/pull/3330

**Comment by sequentiality** [comment]
@adschm moved the conversation there.
