### ISSUE TITLE
OpenWrt 19.07.5

### ISSUE THREAD

**Issue by sequentiality** [ioiotor/mir4-ss#4]
Hi @ioiotor
Any plans to build https://openwrt.org/releases/19.07/notes-19.07.5 for mir4? Thanks
BTW, what is the difference between this repo and https://github.com/ioiotor/mir4-openwrt?

**Comment by ioiotor** [comment]
@sequentiality 
you can use   https://raw.githubusercontent.com/ioiotor/OpenWrt-Autobuild/master/.github/workflows/mirouter-4.yaml
&  https://raw.githubusercontent.com/ioiotor/OpenWrt-Autobuild/master/.github/workflows/mirouter-4.yaml  build it .
but it will compile all device firmware  and packages .  If you have time, you can test the compiled firmware.


mirouter-4.yaml    (  based on openwrt/releases/19.07.5/targets/ramips/mt7621/config.buildinfo file)

**Comment by sequentiality** [comment]
https://github.com/sequentiality/openwrt/releases/tag/v19.07.5
